import Vue from "vue";
import More from "./library/more.vue";
import Skeleton from "./library/skeleton";
import Bread from "./library/bread";
import BreadItem from "./library/bread-item";
import City from "./library/city";
import XtxButton from "./library/xtx-button.vue";
import XtxNumber from "./library/XtxNumber";
import XtxDialog from "./library/xtx-dialog";
Vue.component("More", More);
Vue.component("Skeleton", Skeleton);
Vue.component("Bread", Bread);
Vue.component("BreadItem", BreadItem);
Vue.component("City", City);
Vue.component("XtxButton", XtxButton);
Vue.component("XtxNumber", XtxNumber);
Vue.component("XtxDialog", XtxDialog);
